SELECT * FROM EMPLOYEEINFO;


SELECT EMPFNAME||' '||EMPLNAME AS "NAME" , ADDRESS FROM EMPLOYEEINFO;


SELECT COUNT(*) AS "NO.OF.ROWS" FROM EMPLOYEEINFO;


SELECT EMPFNAME FROM EMPLOYEEINFO;


SELECT PROJECT FROM EMPLOYEEINFO;


SELECT DEPARTMENT FROM EMPLOYEEINFO;


SELECT GENDER FROM EMPLOYEEINFO;


SELECT EMPFNAME FROM EMPLOYEEINFO WHERE EMPFNAME LIKE 'Sa%';


SELECT DEPARTMENT FROM EMPLOYEEINFO WHERE DEPARTMENT = 'HR';


SELECT ADDRESS FROM EMPLOYEEINFO WHERE ADDRESS = 'Hyderabad(HYD)';