SELECT FIRST||' '||LAST AS "STUDENT_NAMES" , TO_CHAR(BIRTHDATE , 'YYYY, DDth MONTH') AS "BIRTHDATE" FROM STUDENT;

CREATE USER CHILD IDENTIFIED BY kiit;
GRANT CONNECT TO CHILD;

GRANT SELECT ON TERM TO CHILD;

REVOKE SELECT ON TERM FROM CHILD;
/* OR REVOKE ALL ON TERM FROM CHILD; */


DROP USER CHILD;


SELECT COUNT(*) , ROOMTYPE FROM LOCATION GROUP BY ROOMTYPE;


SELECT COUNT(ROOMNO) , BUILDING FROM LOCATION GROUP BY BUILDING;


SELECT AVG(MAXCOUNT) , TERMID FROM CRSSECTION GROUP BY TERMID;


SELECT MAX(MAXCOUNT) , TERMID FROM CRSSECTION GROUP BY TERMID;


SELECT MAX(MAXCOUNT) , COURSEID FROM CRSSECTION GROUP BY COURSEID ORDER BY MAX(MAXCOUNT) ASC;


SELECT * FROM CRSSECTION ORDER BY COURSEID ASC , TERMID DESC;


SELECT * FROM CRSSECTION ORDER BY TERMID ASC , COURSEID DESC;


SELECT COUNT(STUDENTID) , MIDTERM FROM REGISTRATION GROUP BY MIDTERM;

/* YES THE NULL GRADES ARE ALSO CONSIDERED BECAUSE NULL IS ALSO BEEN TAKEN AS A TYPE OF VALUE FOR THE ATTRIBUTE MIDTERM GRADES. */


CREATE TABLE STUDENT_DETAILS AS SELECT STUDENTID , FIRST , LAST , STREET , CITY , STATE , ZIP , BIRTHDATE , PHONE FROM STUDENT;


SELECT TABLE_NAME FROM USER_TABLES;


DESC STUDENT_DETAILS;


DROP TABLE STUDENT_DETAILS;